# Generated by Django 2.2.2 on 2019-06-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObsField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_no', models.IntegerField()),
                ('field_name', models.CharField(max_length=90, unique=True)),
                ('ra', models.DecimalField(decimal_places=5, max_digits=8)),
                ('dec', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_id', models.CharField(max_length=5)),
                ('sat_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('field_status', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObsRecords',
            fields=[
                ('idobs_records', models.AutoField(primary_key=True, serialize=False)),
                ('star_id', models.CharField(max_length=45)),
                ('star_name', models.CharField(blank=True, max_length=45, null=True)),
                ('sp_type', models.CharField(blank=True, max_length=45, null=True)),
                ('obs_start', models.CharField(max_length=45)),
                ('obs_end', models.CharField(max_length=45)),
                ('no_obs', models.IntegerField()),
                ('obs_mode', models.CharField(max_length=10)),
                ('availability', models.CharField(max_length=45)),
                ('setup', models.IntegerField()),
                ('field_no', models.ForeignKey(db_column='field_no', on_delete=django.db.models.deletion.DO_NOTHING, to='observations.ObsField')),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='observations.Satellite')),
            ],
        ),
        migrations.AddField(
            model_name='obsfield',
            name='field_status',
            field=models.ForeignKey(db_column='field_status', on_delete=django.db.models.deletion.CASCADE, to='observations.Status'),
        ),
    ]
