# Generated by Django 2.2.2 on 2019-06-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsrecords',
            name='field_no',
            field=models.ForeignKey(db_column='field_no', on_delete=django.db.models.deletion.CASCADE, to='observations.ObsField'),
        ),
        migrations.AlterField(
            model_name='obsrecords',
            name='sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Satellite'),
        ),
    ]
