# Generated by Django 2.2.2 on 2019-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20190609_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obsrecords',
            name='no_obs',
        ),
        migrations.RemoveField(
            model_name='obsrecords',
            name='star_id',
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='exptime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='hd_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='norg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='nred',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='nstack',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='v_mag',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='xpos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='xsize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='ypos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='ysize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obsrecords',
            name='availability',
            field=models.CharField(default='PP', max_length=45),
        ),
        migrations.AlterField(
            model_name='obsrecords',
            name='obs_end',
            field=models.DecimalField(decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='obsrecords',
            name='obs_start',
            field=models.DecimalField(decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='obsrecords',
            name='setup',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
