# Generated by Django 2.2.2 on 2019-06-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20190616_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsrecords',
            name='sat',
            field=models.ForeignKey(db_column='sat_id', on_delete=django.db.models.deletion.CASCADE, to='observations.Satellite'),
        ),
    ]
