# Generated by Django 2.2.2 on 2019-06-27 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20190616_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obsrecords',
            name='field_no',
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.ObsField'),
        ),
    ]
