# Generated by Django 2.2.2 on 2019-07-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_auto_20190627_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsrecords',
            name='data_release',
            field=models.CharField(default='R5', max_length=3),
        ),
    ]
