# Generated by Django 2.2.2 on 2019-07-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_obsrecords_data_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('initials', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=90)),
            ],
        ),
        migrations.RemoveField(
            model_name='obsrecords',
            name='hd_num',
        ),
        migrations.RemoveField(
            model_name='obsrecords',
            name='sp_type',
        ),
        migrations.RemoveField(
            model_name='obsrecords',
            name='star_name',
        ),
        migrations.RemoveField(
            model_name='obsrecords',
            name='v_mag',
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_num', models.IntegerField(null=True)),
                ('v_mag', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('sp_type', models.CharField(blank=True, max_length=45, null=True)),
                ('star_name', models.CharField(blank=True, max_length=45, null=True)),
                ('pi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.PrincInv')),
            ],
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Stars'),
        ),
    ]
