# Generated by Django 2.2.2 on 2019-07-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_auto_20190720_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stars',
            name='pi',
        ),
        migrations.DeleteModel(
            name='PrincInv',
        ),
    ]
