# Generated by Django 2.2.2 on 2019-07-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_auto_20190720_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('initials', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stars',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.PrincInv'),
        ),
    ]
