# Generated by Django 2.2.2 on 2019-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_auto_20190720_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='hd_num',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
