# Generated by Django 2.2.2 on 2019-07-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_auto_20190720_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='hd_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
