# Generated by Django 2.2.2 on 2019-07-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_auto_20190720_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='star_name',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
