# Generated by Django 2.2.2 on 2019-07-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_auto_20190720_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obsrecords',
            name='field',
        ),
        migrations.AddField(
            model_name='stars',
            name='availability',
            field=models.CharField(default='PP', max_length=45),
        ),
        migrations.AddField(
            model_name='stars',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.ObsField'),
        ),
    ]
